### ISSUE TITLE
How can I expose markdown asset files (static)?

### ISSUE THREAD

**Issue by stephane-klein** [ota-meshi/vite-plugin-svelte-md#25]
Hello,

If I have this content in [`/src/routes/garden/017-equipement.md` markdown file](https://github.com/stephane-klein/sklein.xyz/blob/e7466166c495cb61054750beb317de82ba02d318/src/routes/garden/017-equipement.md?plain=1#L7):

```
# Équipement

<img src="images/office.jpg" style="margin: 2rem auto; display: block; width: 100%" />

...
```

How can I expose `/src/routes/garden/images/office.jpg` file?

**Comment by stephane-klein** [comment]
@ota-meshi

**Comment by ota-meshi** [comment]
I think it's the same as the svelte component.
https://kit.svelte.dev/docs/assets
Use svelte-preprocess-import-assets.
https://github.com/bluwy/svelte-preprocess-import-assets

**Comment by stephane-klein** [comment]
I set up https://github.com/bluwy/svelte-preprocess-import-assets with success in [this branch](https://github.com/stephane-klein/sklein.xyz/commit/5dd3a975fc4c366f225dae3f137044bc81760c54)

I still need to fix issue: ` style="margin: 2rem auto; display: block; width: 100%" />` is ignored.

**Comment by ota-meshi** [comment]
What does "ignored" mean?

**Comment by ota-meshi** [comment]
I don't think it has been ignored.

![image](https://user-images.githubusercontent.com/16508807/182577662-d66d6031-20d8-4b01-b20f-a2adcdbdba05.png)

**Comment by ota-meshi** [comment]
Anyway, I think the first issue has been resolved, so I close this issue. If you have a new problem, please open a new issue.

**Comment by stephane-klein** [comment]
> What does "ignored" mean?

Indeed, I did not pay enought attention, there is no problem :+1:.
