### ISSUE TITLE
How can I get access to frontmatter in __layout.svelte?

### ISSUE THREAD

**Issue by stephane-klein** [ota-meshi/vite-plugin-svelte-md#26]
Hi,

I setup `vite-plugin-svelte-md` with success in a SvelteKit project: https://github.com/stephane-klein/sklein.xyz/tree/c4e80fe6abe621f68e669dd5a375ef01eda92470

Question: [here](https://github.com/stephane-klein/sklein.xyz/blob/1a6d86adae43b240e60ba4743b868d3b945023da/src/routes/garden/__layout.svelte#L6), how can I get access to markdown `frontmatter` in `__layout.svelte`?

Suggestion: what do you think to document this method in `README.md`?

Best regards,  
Stéphane

**Comment by stephane-klein** [comment]
@ota-meshi an idea?

**Comment by ota-meshi** [comment]
`__layout.svelte` may be deprecated, but for now I think you can get the `frontmatter` with:

```svelte
<script context="module">
  const docs = import.meta.glob("./**/*.md")

  /** @type {import('@sveltejs/kit').Load} */
  export async function load({ url }) {
    const key = `./${toMarkdownPath(url.pathname)}`
    if (docs[key]) {
      return {
        props: {
          frontmatter: (await docs[key]()).frontmatter,
        },
      }
    }
    // ...
  }
</script>
```

> Suggestion: what do you think to document this method in README.md?

The document may be of value after the Svelte Kit reaches GA.

**Comment by stephane-klein** [comment]
@ota-meshi thanks ♥️

Question: where is defined `toMarkdownPath`?

**Comment by ota-meshi** [comment]
`toMarkdownPath` function depends on your environment. (Such as slashes and baseURL.)
It's a function that converts a URL's PATH to a markdown PATH.
