### ISSUE TITLE
Refactoring to new sveltekit filesystem-based router

### ISSUE THREAD

**Issue by stephane-klein** [ota-meshi/vite-plugin-svelte-md#27]
Following this [breaking change](https://github.com/sveltejs/kit/releases/tag/%40sveltejs%2Fkit%401.0.0-next.406), I think that [vite-plugin-svelte-md](https://github.com/ota-meshi/vite-plugin-svelte-md/blob/bd7f4d44d4258ff47c895e6b39ae581535cfe6e5/src/index.ts#L26) must be refactored, isn't it?

Filesystem-based router: https://github.com/sveltejs/kit/discussions/5774 https://github.com/sveltejs/kit/pull/5778

**Comment by ota-meshi** [comment]
The configuration for use with SvelteKit may change, but since this is just a vite plugin, I don't think the plugin itself needs to be changed.

**Comment by ota-meshi** [comment]
I have checked that it works using `+page.md`. Preprocessing may be necessary if you want to keep the files so far.
